import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { DemoStateProvider } from "@/components/demo-state";
import { SettingsPanel } from "@/components/ui/SettingsPanel";
import "./globals.css";

const workSans = Work_Sans({
  variable: "--font-work-sans-loader",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={workSans.variable} suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400,500,700,900&display=swap"
        />
      </head>
      <body>
        <ThemeProvider attribute="data-theme" defaultTheme="system" enableSystem>
          <DemoStateProvider>
            {children}
            <SettingsPanel />
          </DemoStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
