export type ComponentStatus = "planned" | "built";

export type ComponentEntry = {
  slug: string;
  name: string;
  category: "Atom" | "Molecule" | "Organism";
  desc: string;
  usedIn: string[];
  status: ComponentStatus;
};

export const catalog: ComponentEntry[] = [
  // Atoms
  {
    slug: "button",
    name: "Button",
    category: "Atom",
    desc: "Primary/secondary/ghost/destructive/accent variants, 4 sizes (sm/md/lg/xl), disabled state. Primary/Secondary/Accent/Destructive all get a glossy shimmer-ring overlay; Ghost doesn't.",
    usedIn: [
      "Create Campaign CTA",
      "Launch button",
      "Pause/Archive",
      "Copy actions",
    ],
    status: "built",
  },
  {
    slug: "input",
    name: "Input",
    category: "Atom",
    desc: "Single-line text field. Default/hover/focus/error states, single fixed size.",
    usedIn: ["Campaign title", "Campaign heading", "CTA link", "Budget amount"],
    status: "built",
  },
  {
    slug: "textarea",
    name: "Textarea",
    category: "Atom",
    desc: "Multi-line text box. Same state set as Input.",
    usedIn: ["Ad content — Body text"],
    status: "built",
  },
  {
    slug: "select",
    name: "Select",
    category: "Atom",
    desc: "Custom dropdown (not native) — styled trigger + portaled listbox.",
    usedIn: ["Campaign List filters — Status, Objective"],
    status: "built",
  },
  {
    slug: "date-picker",
    name: "Date Picker",
    category: "Atom",
    desc: "Custom calendar popover with month/year pill dropdowns — single date or range (two calendars, From/To) mode.",
    usedIn: [
      "Budget & time duration — Start/End date",
      "Campaign List — Date range filter",
    ],
    status: "built",
  },
  {
    slug: "switch",
    name: "Switch",
    category: "Atom",
    desc: "On/off toggle. Default/hover/focus states for both off and on, plus disabled.",
    usedIn: ["Settings — Notification toggles"],
    status: "built",
  },
  {
    slug: "badge",
    name: "Badge",
    category: "Atom",
    desc: "Small status pill — 8 generic color tones (incl. purple, amber), callers map them to statuses.",
    usedIn: [
      "Campaign List — Status badge",
      "IA page — Scope tags",
      "Cost Breakdown pills",
    ],
    status: "built",
  },
  {
    slug: "tooltip",
    name: "Tooltip",
    category: "Atom",
    desc: 'Hover/focus info bubble, portaled to escape clipping containers. Wraps a custom trigger or defaults to an "i" badge.',
    usedIn: ["IA page — screen rationale"],
    status: "built",
  },
  {
    slug: "icon-button",
    name: "Icon Button",
    category: "Atom",
    desc: "Small icon-only button — same 5 variants as Button (reuses its color CSS), 3 square sizes.",
    usedIn: [
      "Platform Integration — API keys list",
      "Pixel Tracking — install snippet",
    ],
    status: "built",
  },
  {
    slug: "divider",
    name: "Divider",
    category: "Atom",
    desc: "Thin rule, horizontal or vertical.",
    usedIn: ["Card internals", "Settings sections"],
    status: "built",
  },
  {
    slug: "radio",
    name: "Radio",
    category: "Atom",
    desc: "Single-select circular control with a label. Default/hover/focus/checked states.",
    usedIn: ["Range Filter — Daily/Weekly/Monthly options"],
    status: "built",
  },
  {
    slug: "otp-input",
    name: "OTP Input",
    category: "Atom",
    desc: "6-digit-box code entry — auto-advance, backspace-back, paste-to-fill.",
    usedIn: ["Login/Signup"],
    status: "built",
  },
  {
    slug: "skeleton",
    name: "Skeleton",
    category: "Atom",
    desc: "Shimmering placeholder block — text/rect/circle variants. The primitive every data-bearing component composes for its loading state.",
    usedIn: [
      "KPI Tile",
      "KPI Small Strip",
      "Table",
      "Campaign Card Grid",
      "Activity Feed",
      "Trend Chart",
      "Stacked Bar Chart",
    ],
    status: "built",
  },
  {
    slug: "dot-swirl",
    name: "Dot Swirl",
    category: "Atom",
    desc: "Canvas-drawn monochrome background — a swirl-warped noise field quantized through 4x4 ordered (Bayer) dithering into an ASCII-character grid (shaded by intensity for depth) forming a ring around a fixed empty center; the arms rotate in place. Characters near the pointer swap to a distinct glyph. Respects prefers-reduced-motion (renders one static frame).",
    usedIn: ["Login — left panel"],
    status: "built",
  },
  {
    slug: "carousel-dots",
    name: "Carousel Dots",
    category: "Atom",
    desc: "Pagination dots — the active dot is a pill with a fill bar that animates over a fixed duration and fires a callback on completion (restarting on selection change); other dots are small circles. Clicking any dot jumps to it.",
    usedIn: ["Card Carousel — pagination + auto-advance indicator"],
    status: "built",
  },

  // Molecules
  {
    slug: "kpi-tile",
    name: "KPI Tile",
    category: "Molecule",
    desc: "Icon (per-metric) + label, large value, trend (% + direction color) and a real sparkline built from a data array.",
    usedIn: ["Overview — KPI strip", "Campaign Detail — KPI strip"],
    status: "built",
  },
  {
    slug: "form-field",
    name: "Form Field",
    category: "Molecule",
    desc: "Label (+ optional required mark) + field slot + helper/error text.",
    usedIn: ["Create Campaign wizard", "Settings — Account info form"],
    status: "built",
  },
  {
    slug: "card",
    name: "Card",
    category: "Molecule",
    desc: "Plain padded bordered box, no built-in header.",
    usedIn: ["Needs attention panel", "Payout method setup", "Billing"],
    status: "built",
  },
  {
    slug: "card-carousel",
    name: "Card Carousel",
    category: "Molecule",
    desc: "One card at a time — title + description, Icon Button Prev/Next arrows outside the card navigate manually, and Carousel Dots below show pagination — the active dot's fill bar auto-advances (restarting on manual navigation).",
    usedIn: ["Login — left panel"],
    status: "built",
  },
  {
    slug: "alert-row",
    name: "Alert Row",
    category: "Molecule",
    desc: "Tone-colored row (background/border/icon badge from Badge's tone system) — title, description, top-right arrow as the only affordance; whole row is the click target.",
    usedIn: ["Not currently used — pulled off Overview for now"],
    status: "built",
  },
  {
    slug: "heartbeat-indicator",
    name: "Heartbeat Indicator",
    category: "Molecule",
    desc: 'Bordered API-status card with a beating pixel-block heart (clipped to its own silhouette) over an EKG line, a header refresh button, and a footer status row with a tone-colored icon badge. healthy = Live, warning = Partially Available, critical = Not Live; default/empty state is a static gray card with a flat line, no refresh button ("No API Keys Created"); refreshing state is the same gray look with a fading heart/line, no refresh button, and a spinning footer icon.',
    usedIn: ["Not currently used — demo/prototype component"],
    status: "built",
  },
  {
    slug: "empty-state",
    name: "Empty State",
    category: "Molecule",
    desc: "Icon in concentric halo rings, title + description, up to two Button actions.",
    usedIn: ["Campaign List — zero campaigns"],
    status: "built",
  },
  {
    slug: "tabs",
    name: "Tabs",
    category: "Molecule",
    desc: "Segmented pill control, literally composed from Button (Ghost = inactive; active tab is Primary or Secondary via activeVariant), 3 sizes.",
    usedIn: ["IA page — Advertiser/Platform switch"],
    status: "built",
  },
  {
    slug: "stepper",
    name: "Stepper",
    category: "Molecule",
    desc: "Row of pill segments, filled up to the current step.",
    usedIn: ["Create Campaign — 3-step wizard"],
    status: "built",
  },
  {
    slug: "copy-field",
    name: "Copy Field",
    category: "Molecule",
    desc: "Monospace read-only value + copy Icon Button (checkmark feedback) + optional delete, single or multiline.",
    usedIn: [
      "Platform Integration — API keys, snippet",
      "Pixel Tracking — install snippet",
    ],
    status: "built",
  },
  {
    slug: "code-block",
    name: "Code Block",
    category: "Molecule",
    desc: "Small label above a Copy Field — stacks multiple labeled snippets in sequence.",
    usedIn: [
      "Pixel Tracking — install snippet",
      "Platform Integration — install snippet",
    ],
    status: "built",
  },
  {
    slug: "trend-chart",
    name: "Trend Chart",
    category: "Molecule",
    desc: "Legend (only shown for 2+ series — a single line hides it), a Range Filter (Daily/Weekly/Monthly) plus secondary prev/next pan arrows (with hover Tooltips) that page through the underlying data, minimal or default (axes/gridlines + hatch-filled area) style.",
    usedIn: [
      "Overview — Spend/Revenue-over-time chart",
      "Campaign Detail — Spend over time, Impressions, Conversions over time",
      "Advertiser Events Tracking — Conversions over time, Page visits over time",
    ],
    status: "built",
  },
  {
    slug: "stacked-bar-chart",
    name: "Stacked Bar Chart",
    category: "Molecule",
    desc: "Legend, a Range Filter (Daily/Weekly/Monthly) plus secondary prev/next pan arrows that page through the underlying data — each bar stacks every series that counts toward the total.",
    usedIn: [
      "Overview — Impressions breakdown",
      "Campaign Detail — Impressions breakdown",
    ],
    status: "built",
  },
  {
    slug: "range-filter",
    name: "Range Filter",
    category: "Molecule",
    desc: 'Compact trigger that opens a "Range" popover with Daily/Weekly/Monthly Radio options — a simpler alternative to a full calendar date-range picker.',
    usedIn: ["Trend Chart — granularity control"],
    status: "built",
  },
  {
    slug: "table",
    name: "Table",
    category: "Molecule",
    desc: "Generic, data-driven table shell — columns, sortable headers, row actions, empty state.",
    usedIn: ["Campaign List", "Payout history"],
    status: "built",
  },
  {
    slug: "confirm-dialog",
    name: "Confirm Dialog",
    category: "Molecule",
    desc: "Centered modal — title, description, Cancel (secondary) + Confirm (destructive or primary) actions. Used before any destructive row action.",
    usedIn: [
      "Campaign List — Archive",
      "Platform Integration — revoke API key",
    ],
    status: "built",
  },
  {
    slug: "add-balance-modal",
    name: "Add Balance Modal",
    category: "Molecule",
    desc: "Centered modal for topping up account balance — amount field (min $100), quick-select pills ($200/$500/$1,000/$2,000), Cancel + Add.",
    usedIn: ["Sidebar Nav — balance card", "Billing — Add balance"],
    status: "built",
  },
  {
    slug: "cost-breakdown",
    name: "Cost Breakdown",
    category: "Molecule",
    desc: "Responsive pair — CostBreakdownPills (Badge pills, mobile) and CostBreakdownPanel (a titled Card with dashed-divider rows, tablet/desktop) — same item shape, CSS-only visibility swap at 800px.",
    usedIn: [
      "Advertiser Overview — Spend breakdown",
      "Campaign Detail — Cost breakdown",
    ],
    status: "built",
  },
  {
    slug: "key-manager",
    name: "Key Manager",
    category: "Molecule",
    desc: "Create-key flow — header + Create button, a Table of existing keys (masked value, delete action) or an Empty State, and a one-time reveal Card (Copy Field + Copy key/Done) shown right after creating a new key.",
    usedIn: [
      "Platform Integration — API keys",
      "Advertiser Pixel Setup — Pixel keys",
    ],
    status: "built",
  },

  // Organisms
  {
    slug: "sidebar-nav",
    name: "Sidebar Nav",
    category: "Organism",
    desc: "App shell's left navigation — grouped sections with dotted dividers, green-line active item, collapsible to an icon-only rail. Footer holds an optional balance card (advertiser only), primary action, and account menu.",
    usedIn: ["Whole app shell"],
    status: "built",
  },
  {
    slug: "top-bar",
    name: "Top Bar",
    category: "Organism",
    desc: "Page heading + description, an optional actions slot on the right (e.g. Create Campaign), and an optional back button + breadcrumb for drill-in pages — the account menu moved to a footer pinned at the bottom of Sidebar Nav.",
    usedIn: ["Whole app shell"],
    status: "built",
  },
  {
    slug: "kpi-strip",
    name: "KPI Strip",
    category: "Organism",
    desc: "Row of bordered KPI Tiles (icon, value, trend, sparkline) for a screen — the fuller, more detailed layout. See KPI Compact Strip for the simpler one used on Overview.",
    usedIn: ["Advertiser Events Tracking"],
    status: "built",
  },
  {
    slug: "kpi-small-strip",
    name: "KPI Small Strip",
    category: "Organism",
    desc: "The most minimal KPI variant, from a Figma reference — value + a small bordered icon badge on top (Tooltip trigger, not a button), label below. No trend row. Row orientation by default; column orientation stacks items vertically for a compact side-panel list.",
    usedIn: ["Advertiser Overview", "Platform Overview", "Campaign Detail"],
    status: "built",
  },
  {
    slug: "needs-attention-panel",
    name: "Needs Attention Panel",
    category: "Organism",
    desc: "List of Alert Rows surfacing what needs action right now.",
    usedIn: ["Not currently used — pulled off Overview for now"],
    status: "built",
  },
  {
    slug: "activity-feed",
    name: "Activity Feed",
    category: "Organism",
    desc: "Passive, chronological log of campaign lifecycle, pixel-tracking, and conversion events — a tone-colored icon badge, title, optional description, and relative time per row.",
    usedIn: ["Advertiser Overview — right panel", "Advertiser Events Tracking"],
    status: "built",
  },
  {
    slug: "campaign-table",
    name: "Campaign Table",
    category: "Organism",
    desc: 'Table configured for campaigns — columns, sortable headers, a primary "Manage" row action, empty state.',
    usedIn: ["Campaign List — desktop, Table view"],
    status: "built",
  },
  {
    slug: "campaign-card",
    name: "Campaign Card",
    category: "Organism",
    desc: 'One campaign as a card — name + status badge, a stacked stat list, full-width primary "Manage" button. The mobile/cards-view equivalent of a Campaign Table row.',
    usedIn: ["Campaign List — mobile, and desktop Cards view"],
    status: "built",
  },
  {
    slug: "campaign-card-grid",
    name: "Campaign Card Grid",
    category: "Organism",
    desc: "Responsive grid of Campaign Cards, same empty state as Campaign Table.",
    usedIn: ["Campaign List — mobile, and desktop Cards view"],
    status: "built",
  },
  {
    slug: "create-campaign-wizard",
    name: "Create Campaign Wizard",
    category: "Organism",
    desc: "Stepper + the 3 step forms + final review summary.",
    usedIn: ["Create Campaign"],
    status: "built",
  },
  {
    slug: "history-table",
    name: "History Table",
    category: "Organism",
    desc: "One Table configured two ways — Platform payouts or Advertiser billing invoices. Always sorted latest → oldest, regardless of status.",
    usedIn: ["Platform Earnings", "Advertiser Billing"],
    status: "built",
  },
  {
    slug: "settings-form",
    name: "Settings Form",
    category: "Organism",
    desc: "Account info Form Fields + notification Switches. workspace prop (advertiser/platform) determines the built-in toggle set.",
    usedIn: ["Advertiser Settings", "Platform Settings"],
    status: "built",
  },
  {
    slug: "settings-panel",
    name: "Settings Panel",
    category: "Organism",
    desc: "Pink circular FAB (bottom-right, Gear icon) mounted globally — dark mode, New user (routes to /login), Dashboard switcher (Advertiser/Platform), and force-empty-states/force-loading-states toggles.",
    usedIn: ["Whole app, every page"],
    status: "built",
  },
];

export const categories = ["Atom", "Molecule", "Organism"] as const;
